version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasksdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./server
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/tasksdb
      JWT_SECRET: devsecret
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./server:/app

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./client:/app

volumes:
  db_data: 